### ISSUE TITLE
Generalize the Operator and Support Consul

### ISSUE THREAD

**Issue by ZackButcher** [tetratelabs/istio-cloud-map#32]
Support for Consul in istio/istio has been spotty (it only supports Consul 1.3) and [was removed from upstream](https://github.com/istio/istio/pull/25521/files) (disappearing in Istio 1.8). However, there's been quite a lot of interest in Consul as a service discovery source for Istio. The plan of record in upstream is to move to support Consul via MCP (i.e. consume it as ServiceEntries from another service).

Given asks from customers, we'll should integrate and update the Istio-Consul integration into this codebase (as well as generally stepping up maintenance here).

This will require:
- [ ] Cleaning up the [cloudmap.Store interface](https://github.com/tetratelabs/istio-cloud-map/blob/013ebc194717d6ef696e18c261337a5539caebe7/pkg/cloudmap/store.go#L11-L14)
    - Move the declaration over to the consumer, `pkg/control`
    - Do any work needed to make it play nicely with the previous Istio consul code
- [ ] Bringing the previous istio/istio Consul code over here (with git history/attribution)
    - @nacx can I get some git help from you on this?
- [ ] Update the Consul code to a modern Consul version (it uses 1.3; current version is 1.8)
    - We should investigate compatibility here - I'm not 100% sure what version of Consul it's best for us to cover - by default I assume we should target latest.
- [ ] Fit together the Store interface and the updated istio/istio Consul code

Outside of the code stuffs:
- [ ] Moving over repo name
- [ ] Updating documents
- [ ] Cut a 0.2 release before all this stuff [@ZackButcher] 
- [ ] Cut a 0.3 release after all this stuff

cc @PetrMc

**Comment by nacx** [comment]
>Bringing the previous istio/istio Consul code over here (with git history/attribution)
@nacx can I get some git help from you on this?

Sure, I'll take. care of this

**Comment by mathetake** [comment]
@ZackButcher  @lizan could you give the admin permission of this repo? I would like to push the change officially and push the container to the "renamed" docker repository. This is something to do with getistio (cc @deva26).

**Comment by mathetake** [comment]
I got the admin, and I cut the tag 0.2.0 from https://github.com/tetratelabs/istio-cloud-map/commit/d1214e5654b735620d65ee51caa0c6d4bb3ef6bc which does not includ Consul support. 

As for the renaming this repo, I have two candidates:

- `istio-service-sync-operator`
- `istio-service-synchronizer`

Any ideas @ZackButcher? (cc @deva26)
